version: "3.9"

services:
  notifications-service-web:
    build:
        context: .
        dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code/
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=notifications_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - notifications-service-db
  notifications-service-db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/postgres/data/
    environment:
      - POSTGRES_DB=notifications_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
      postgres_data:
        driver: local
