# Generated by Django 4.2 on 2023-04-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread'), ('deleted', 'Deleted')], max_length=20),
        ),
    ]
